### ISSUE TITLE
%spawn-count% placeholder wrong output + missing lang.

### ISSUE THREAD

**Issue by Ibesh** [BG-Software-LLC/WildStacker#211]
**Minecraft's Version**: 1.17

**Plugin's Version**: 3.6.0-DEVb147

**Describe the bug**:

[**1**] In the `spawner-manage` GUI, the placeholder `%spawn-count%` always displays 4. Probably because you've set the default to 4. 
However the correct amount is shown in the `spawner-upgrade` GUI.

The spawn-count has been set to 1 for the default spawner, but I get an output of 4 in the `spawner-manage` GUI.
![image](https://user-images.githubusercontent.com/43782718/124307659-6d31e400-db68-11eb-8dd5-653145ea4d94.png)

---------------

[**2**] It is not possible to change the text `Current Upgrade:` & `Next Upgrade:` from the `spawner-upgrade` GUI. Probably because this line is missing from the config, spawner-upgrade or language file. Currently they are defaulted to orange, but I'd like a different color. 
![image](https://user-images.githubusercontent.com/43782718/124307993-e16c8780-db68-11eb-95b8-be050dffa992.png)
![image](https://user-images.githubusercontent.com/43782718/124308002-e4677800-db68-11eb-8887-c865b2a15b7a.png)

**To Reproduce**:
[**1**] example config line for my 'default' spawner: https://hatebin.com/isqnmfqpfq

**Additional information**:
[**1**] example config lines from my `spawner-manage` file: https://hatebin.com/kanpsuvvot

**Comment by OmerBenGera** [comment]
About #2 - this is not a bug.
ABout #1 - %spawn-count% shows the correct spawn count of the spawners, and if it shows 4, then it's 4. The upgrade might not have been applied to your spawner due to restrictions you set in config, idk. Anyways, if you think there's a bug with your spawners not having the correct spawner values, make sure you open a new issue describing the bug.
