### ISSUE TITLE
Slimefun incompatibility - Altar Items get renamed

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildStacker#266]
### Minecraft's Version

1.17.1 Purpur 1330

### Plugin's Version

Dev 185

### Describe the bug

When using a slimefun altar and placing the items on the altar they turn into an altar probe and can be picked up.

### To Reproduce

Place a slimefun altar, place items on the altar.

### Additional Information

![unknown](https://user-images.githubusercontent.com/30563757/129458801-d896a3ca-8cde-4e97-a506-2dab58edbd52.png)

The altar basically puts an entity displayed on top of it that is not a real entity, when in relation with a stacker plugin it gets mixed up.

This is usually a problem with a lot of stacker plugins and only recently occurred with WildStacker. Usually this has to do with specific event priorities in relation to Slimefun. With other stackers, modifying the event priority resolves the issue.

**Comment by OmerBenGera** [comment]
WildStacker listens on HIGHEST priority, I don't see how it's an issue with the priorities of the plugin.
What priorities does Slimefun listen on?

**Comment by Skizzles** [comment]
@OmerBenGera I believe they listen on priority HIGH. All I know is when certain stacker plugins have been on higher priority this happens, and it only started recently after past couple days of updates.

I could check each version I updated from but am not currently on the computer.

**Comment by OmerBenGera** [comment]
Why Slimefun not changing the pickup delay to a delay that makes items to never be picked up?
This way, it will work with all the plugins, no matter what plugin is that.

**Comment by Skizzles** [comment]
@OmerBenGera Idk man, they probably never thought of that xD

**Comment by OmerBenGera** [comment]
I think the best solution would be that they give their items the maximum possible pickup delay, which makes items to not be pickable.
Also, they should use a lower priority, this way no other plugin will override their pickup denial. Furthermore, they should look at PlayerAttemptPickupItemEvent (or something like that), which is actually being called before PlayerPickupItemEvent, and cancel that event as well.
I dont want to patch it on my end, because as you said it already happened with other plugins, and the best approach is that they make their plugin compatible with all the other plugins, and not force everyone to add support for their plugin

I will find the pickup delay I was talking about and will post it here later, so the Slimefun developers can chnage their code (the pickup-delay approach is much more optimizes in terms of performance as well)

For now, I am closing this.
