### ISSUE TITLE
Wildstacker conflict with luckperms vault and worldguard

### ISSUE THREAD

**Issue by amarcais53** [BG-Software-LLC/WildStacker#389]
### Minecraft's Version

his server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)

### Plugin's Version

wildstacker b232

### Describe the bug

im getting spammed on my console and when it spam my server freeze on the stack tace i saw that 
com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation keeps player references in the memory

here is the paste bin
https://pastebin.com/n2tLCSXV

### To Reproduce

im not sure how to reproduce this never happen before

**Comment by OmerBenGera** [comment]
This is not related to WildStacker.
What happens is that WildStacker fires the EntityDeathEvent itself, which is why you see it there. However, what triggers the error is WorldGuard. It happens when WildStacker fires the event, as WorldGuard has a listener to the EntityDeathEvent.
What I believe that happens is when WildStacker calls EntityDeathEvent, WorldGuard checks for things somehow with Vault, which triggers the error.

Once you disable whatever triggers WorldGuard to hook with Vault, it will work.

**Comment by amarcais53** [comment]
after talking to worldguard they said that 

https://github.com/BG-Software-LLC/WildStacker/blob/master/src/main/java/com/bgsoftware/wildstacker/utils/entity/logic/DeathSimulation.java#L61 see that Player killer bit
that's the reference to the player that they are holding in memory - a player that's already been logged out

**Comment by amarcais53** [comment]
@OmerBenGera

**Comment by OmerBenGera** [comment]
> after talking to worldguard they said that
> 
> https://github.com/BG-Software-LLC/WildStacker/blob/master/src/main/java/com/bgsoftware/wildstacker/utils/entity/logic/DeathSimulation.java#L61 see that Player killer bit that's the reference to the player that they are holding in memory - a player that's already been logged out

That's a parameter of WildStacker method, and the player is guaranteed to be online at that time.
