### ISSUE TITLE
WildStacker bug with CMI holograms

### ISSUE THREAD

**Issue by NoltoxGit** [BG-Software-LLC/WildStacker#643]
### Minecraft's Version

purpur-1.19.2-1820.jar

### Plugin's Version

WildStacker-2022.5-b376.jar

### Describe the bug

When I start the server with CMI and WildStacker, the CMI holograms are removed.
And this requires CMI to recalculate them entirely.

I can confirm that this bug comes from WildStacker because when I disable your plugin, the holograms load correctly.

### To Reproduce

- Start server with latest purpur build
- Start server with latest cmi version
- Start server with latest WildStackers build
- Look the console of the server

### Additional Information

Logs: https://mclo.gs/SsrrRGD
Config: https://pastebin.com/Hdt5W0fp

**Comment by OmerBenGera** [comment]
When do they get removed?

**Comment by NoltoxGit** [comment]
> When do they get removed?

From line [316](https://mclo.gs/SsrrRGD#L316) through [338](https://mclo.gs/SsrrRGD#L338).

**Comment by OmerBenGera** [comment]
> > When do they get removed?
> 
> From line [316](https://mclo.gs/SsrrRGD#L316) through [338](https://mclo.gs/SsrrRGD#L338).

These warnings are from CMI and they are regarding the worlds not loading at the time the holograms are loaded.
This might be because of dependencies racing with each other - WildStacker tries to load before X, CMI after Y and it's somehow broken.

Not an issue that really can be fixed. CMI should try and actually load the holograms again as they state they do.
