### ISSUE TITLE
WildStacker high CPU usage

### ISSUE THREAD

**Issue by SrMonsterYT** [BG-Software-LLC/WildStacker#715]
### Minecraft's Version

git-Pufferfish-42 (MC: 1.19.2)

### Plugin's Version

WildStacker-2022.6-b406.jar

### Describe the bug

https://timings.aikar.co/dev/?id=3259ba020d904cf1bfa39cebdb8391d4#timings

### To Reproduce

I don't know how to play but the server has 60 players and the wildstacker is using 7% of the CPU, is that normal?

**Comment by OmerBenGera** [comment]
The lag comes from DeathSimulation, which makes me believe it's another plugin causing this to occur.
This is because WildStacker is calling EntityDamageEvent/EntityDeathEvent, and if other plugins cause lag in these events, it will show under WildStacker.
Take a spark profiler so we can fully understand what is the root cause of the lag.

**Comment by OmerBenGera** [comment]
Take another spark profiler, it shows WildStacker with barely 1% of thread usage.

**Comment by SrMonsterYT** [comment]
10m -> https://spark.lucko.me/n4ezbwrGrl

**Comment by OmerBenGera** [comment]
It looks fine for me tbh.
Anyways, as I said before, WildStacker is not the main lag source on your server.
I'd recommend focusing on the plugins that actually take almost 25% of the thread usage and not WildStacker which only takes around 1%.
